version: '2'
services:
  nginx:
    mem_limit: 256
    image: 248536655549.dkr.ecr.us-west-2.amazonaws.com/reverse-proxy
    ports:
      - 80:80
    links:
      - app
  app:
    mem_limit: 256
    image: 248536655549.dkr.ecr.us-west-2.amazonaws.com/kffp-shop
