version: '2'
services:
  app:
    mem_limit: 256MB
    # build:
    #   context: .
    image: 248536655549.dkr.ecr.us-west-2.amazonaws.com/kffp-shop

  nginx:
    mem_limit: 256MB
    # build:
    #   context: './docker/nginx'
    image: 248536655549.dkr.ecr.us-west-2.amazonaws.com/reverse-proxy
    ports:
      - 80:80
    links:
      - app
